name_or_path: /fs-computility/llmit_d/shared/zhangchi/wjc/Llama3-8B-Base
tokenizer_name_or_path: null
archive: null
block_name: LlamaDecoderLayer
reference_name_or_path: null
policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16
