name_or_path: /fs-computility/llmit_d/shared/zhangchi/wjc/Qwen3-1.7B
tokenizer_name_or_path: null
archive: null
block_name: Qwen3DecoderLayer
reference_name_or_path: null
policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16